import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html>
//       <body className="bg-gray-100 min-h-screen">
//         <header className="bg-blue-600 text-white p-4">
//           <h1 className="text-xl font-bold">Library App</h1>
//           <nav className="mt-2">
//             <a href="/authors" className="mr-4">Authors</a>
//             <a href="/books">Books</a>
//           </nav>
//         </header>
//         <main className="p-6">{children}</main>
//       </body>
//     </html>
//   );
// }


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
